# docker-compose -p gamesland-api-test up --build
version: "3.3"
services:
  persistence:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: gamesland-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"